version: '3'

services:
  development:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/work
    depends_on:
      - lambda
  lambda:
    build: ./
    ports:
      - 9000:8080
    environment:
      - ENDPOINT_URL=http://localstack:4566
      - ENV=development
      - AWS_ACCESS_KEY_ID=_
      - AWS_SECRET_ACCESS_KEY=_
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"